version: "3.8"

services:
  auth-service:
    image: tspdevsecops/chatroom-auth:latest
    ports:
      - "3001:3001"
    restart: unless-stopped

  file-service:
    image: tspdevsecops/chatroom-file:latest
    ports:
      - "3002:3002"
    volumes:
      - file-uploads:/app/uploads
    restart: unless-stopped

  backend:
    image: tspdevsecops/chatroom-backend:latest
    ports:
      - "8080:8080"
    restart: unless-stopped

  frontend:
    image: tspdevsecops/chatroom-frontend:latest
    ports:
      - "5173:80"
    restart: unless-stopped

volumes:
  file-uploads:
